name: registry-aeson
version: 0.1.0.0
synopsis: Aeson encoders / decoders

description: This library provides encoders / decoders which can be easily customized for the Aeson format.

extra-source-files: README.md

category: Data

license: MIT
license-file: LICENSE.txt

maintainer: etorreborre@yahoo.com
git: https://github.com/etorreborre/registry-aeson

ghc-options: -Wall
  -Wcompat
  -Wincomplete-record-updates
  -fhide-source-paths
  -fprint-potential-instances
  -fno-warn-partial-type-signatures
  -optP-Wno-nonportable-include-path

default-extensions:
  - BangPatterns
  - DefaultSignatures
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - DerivingVia
  - DerivingStrategies
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - Rank2Types
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

dependencies:
  - base                 >= 4.7   && < 5
  - containers           >= 0.2   && < 1
  - aeson                >= 1     && < 2
  - bytestring           >= 0.10  && < 1
  - protolude            >= 0.3   && < 0.4
  - registry             >= 0.2   && < 0.3
  - template-haskell     >= 2.13  && < 3.0
  - text                 >= 1     && < 2
  - transformers         >= 0.5   && < 2
  - unordered-containers >= 0.2   && < 1
  - vector               >= 0.1   && < 1

library:
  source-dirs: src

  ghc-options: -Wincomplete-uni-patterns

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies:
      - registry-hedgehog
      - registry-aeson
      - tasty
      - time

    ghc-options: -threaded
      -rtsopts
      -with-rtsopts=-N
      -fno-warn-orphans
      -fno-warn-missing-signatures
      -fno-warn-incomplete-uni-patterns
      -fno-warn-type-defaults
      -optP-Wno-nonportable-include-path
